export const BACKEND_DEMO_PRODUCTS = [
  // 1. Kaja Specials
  {
    id: 'c1000000-0000-0000-0000-000000000001',
    name: 'Kakinada Gottam Kaja (Pure Ghee)',
    slug: 'kakinada-gottam-kaja',
    image_url: '/sweets/kakinada-gottam-kaja.jpg',
    description: 'The iconic jewel of Andhra Pradesh. Cylindrical golden pastry, crispy on the outer shell and filled with warm, aromatic cardamom sugar syrup in the center.',
    price: 320.00,
    weight: '500g',
    ingredients: 'Refined Wheat Flour (Maida), Pure Country Ghee, Sugar Syrup, Cardamom Powder.',
    taste_profile: 'Crispy outer crust with a juicy, melt-in-mouth sugary cardamom syrup center.',
    allergens: 'Contains Gluten (Wheat) and Dairy (Ghee).',
    shelf_life: '15 Days from packing date.',
    storage_instructions: 'Store in an airtight container at room temperature away from direct sunlight. Do not refrigerate.',
    stock: 85,
    is_available: true,
    rating: 4.95,
    review_count: 148,
    categories: { name: 'Kaja Specials' },
    product_images: [{ image_url: '/sweets/kakinada-gottam-kaja.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000002',
    name: 'Ghee Kaja (Nethi Kaja)',
    slug: 'ghee-kaja',
    image_url: '/sweets/ghee-kaja.jpg',
    description: 'Authentic royal Nethi Kaja prepared with 100% pure desi cow ghee, delicately layered and drenched in fragrant cardamom sugar syrup.',
    price: 350.00,
    weight: '500g',
    ingredients: 'Refined Wheat Flour, Pure Desi Cow Ghee, Cane Sugar, Cardamom Powder.',
    taste_profile: 'Rich ghee aroma, crispy outside and oozing with sweet syrup.',
    allergens: 'Contains Gluten and Dairy.',
    shelf_life: '15 Days from packing date.',
    storage_instructions: 'Store at room temperature in an airtight box.',
    stock: 75,
    is_available: true,
    rating: 4.96,
    review_count: 112,
    categories: { name: 'Kaja Specials' },
    product_images: [{ image_url: '/sweets/ghee-kaja.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000003',
    name: 'Madatha Kaja',
    slug: 'madatha-kaja',
    image_url: '/sweets/madatha-kaja.jpg',
    description: 'Traditional folded layered sweet delicacy, crispy and flaky on the outside with syrupy sweetness trapped between delicate pastry layers.',
    price: 280.00,
    weight: '500g',
    ingredients: 'Refined Wheat Flour, Pure Ghee, Sugar, Cardamom.',
    taste_profile: 'Flaky, crunchy layered texture with rich sugar infusion.',
    allergens: 'Contains Gluten and Dairy.',
    shelf_life: '15 Days from packing date.',
    storage_instructions: 'Store in cool dry airtight container.',
    stock: 60,
    is_available: true,
    rating: 4.80,
    review_count: 92,
    categories: { name: 'Kaja Specials' },
    product_images: [{ image_url: '/sweets/madatha-kaja.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000004',
    name: 'Baby Madatha Kaja',
    slug: 'baby-madatha-kaja',
    image_url: '/sweets/baby-madatha-kaja.jpg',
    description: 'Bite-sized miniature layered Madatha Kajas, perfectly crisp, flaky and dipped in rich cardamom syrup for delightful single-bite enjoyment.',
    price: 290.00,
    weight: '500g',
    ingredients: 'Refined Wheat Flour, Pure Ghee, Cane Sugar, Cardamom.',
    taste_profile: 'Crisp bite-sized flaky pastry soaked in fragrant sweet syrup.',
    allergens: 'Contains Gluten and Dairy.',
    shelf_life: '15 Days from packing date.',
    storage_instructions: 'Store in an airtight container at room temperature.',
    stock: 65,
    is_available: true,
    rating: 4.88,
    review_count: 76,
    categories: { name: 'Kaja Specials' },
    product_images: [{ image_url: '/sweets/baby-madatha-kaja.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000005',
    name: 'Baby Gottam Kaja',
    slug: 'baby-gottam-kaja',
    image_url: '/sweets/baby-gottam-kaja.jpg',
    description: 'Miniature version of the world-famous Kakinada Gottam Kaja with a crunchy cylindrical outer crust holding luscious warm cardamom syrup.',
    price: 330.00,
    weight: '500g',
    ingredients: 'Refined Wheat Flour, Pure Country Ghee, Sugar, Cardamom.',
    taste_profile: 'Crispy bite-sized crust filled with sweet cardamom syrup.',
    allergens: 'Contains Gluten and Dairy.',
    shelf_life: '15 Days from packing date.',
    storage_instructions: 'Store at room temperature in an airtight box.',
    stock: 70,
    is_available: true,
    rating: 4.92,
    review_count: 88,
    categories: { name: 'Kaja Specials' },
    product_images: [{ image_url: '/sweets/baby-gottam-kaja.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000006',
    name: 'Paneer Kaja',
    slug: 'paneer-kaja',
    image_url: '/sweets/paneer-kaja.jpg',
    description: 'Soft and porous kaja variety enriched with fresh cottage cheese (chenna) and infused with light aromatic sugar syrup.',
    price: 340.00,
    weight: '500g',
    ingredients: 'Fresh Paneer (Chenna), Wheat Flour, Pure Ghee, Sugar Syrup, Cardamom.',
    taste_profile: 'Soft, spongy texture with rich dairy sweetness and cardamom notes.',
    allergens: 'Contains Gluten and Dairy.',
    shelf_life: '10 Days from packing date.',
    storage_instructions: 'Store in an airtight container.',
    stock: 50,
    is_available: true,
    rating: 4.85,
    review_count: 62,
    categories: { name: 'Kaja Specials' },
    product_images: [{ image_url: '/sweets/paneer-kaja.jpg', is_primary: true }],
  },

  // 2. Traditional Sweets
  {
    id: 'c1000000-0000-0000-0000-000000000007',
    name: 'Kaju Barfi',
    slug: 'kaju-barfi',
    image_url: '/sweets/kaju-barfi.jpg',
    description: 'Soft and rich cashew-based sweet with a smooth texture, suitable for festive occasions and gifting.',
    price: 520.00,
    weight: '500g',
    ingredients: 'Premium Cashew Nuts (Kaju), Sugar, Pure Ghee, Cardamom.',
    taste_profile: 'Smooth, subtle sweetness with prominent nutty richness and melt-in-mouth finish.',
    allergens: 'Contains Tree Nuts (Cashew) and Dairy.',
    shelf_life: '20 Days from packing date.',
    storage_instructions: 'Keep in cool, dry place. Refrigerator recommended during summer.',
    stock: 65,
    is_available: true,
    rating: 4.94,
    review_count: 210,
    categories: { name: 'Traditional Sweets' },
    product_images: [{ image_url: '/sweets/kaju-barfi.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000008',
    name: 'Gulab Jamun',
    slug: 'gulab-jamun',
    image_url: '/sweets/gulab-jamun.jpg',
    description: 'Soft, syrup-soaked milk-based sweet with a rich and traditional taste.',
    price: 290.00,
    weight: '500g',
    ingredients: 'Khoya (Mawa), Milk Solids, Cane Sugar, Green Cardamom, Rose Water, Pure Ghee.',
    taste_profile: 'Extremely soft, juicy, warm cardamom-rose infused sweetness.',
    allergens: 'Contains Dairy.',
    shelf_life: '7 Days from packing date.',
    storage_instructions: 'Store in a cool dry place or refrigerate in an airtight container.',
    stock: 80,
    is_available: true,
    rating: 4.91,
    review_count: 175,
    categories: { name: 'Traditional Sweets' },
    product_images: [{ image_url: '/sweets/gulab-jamun.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000009',
    name: 'Jangri',
    slug: 'jangri',
    image_url: '/sweets/jangri.jpg',
    description: 'Traditional spiral-shaped sweet with a crisp exterior and juicy syrup-filled center.',
    price: 310.00,
    weight: '500g',
    ingredients: 'Urad Dal (Black Gram), Pure Ghee, Sugar Syrup, Saffron, Cardamom, Lemon juice.',
    taste_profile: 'Juicy, syrupy and chewy with rich floral notes.',
    allergens: 'Contains Dairy.',
    shelf_life: '8 Days from packing date.',
    storage_instructions: 'Airtight container at room temperature.',
    stock: 50,
    is_available: true,
    rating: 4.86,
    review_count: 89,
    categories: { name: 'Traditional Sweets' },
    product_images: [{ image_url: '/sweets/jangri.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000010',
    name: 'Paneer Jalebi',
    slug: 'paneer-jalebi',
    image_url: '/sweets/paneer-jalebi.jpg',
    description: 'Festive spiral delicacy prepared with fresh cottage cheese (paneer), golden fried in pure ghee and soaked in saffron sugar syrup.',
    price: 330.00,
    weight: '500g',
    ingredients: 'Fresh Paneer (Chenna), Milk Solids, Pure Ghee, Saffron, Sugar, Cardamom.',
    taste_profile: 'Melt-in-the-mouth, juicy, rich and delicately aromatic with saffron notes.',
    allergens: 'Contains Dairy.',
    shelf_life: '6 Days from packing date.',
    storage_instructions: 'Store in a cool dry place or refrigerate.',
    stock: 45,
    is_available: true,
    rating: 4.87,
    review_count: 54,
    categories: { name: 'Traditional Sweets' },
    product_images: [{ image_url: '/sweets/paneer-jalebi.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000020',
    name: 'Sunnundalu',
    slug: 'sunnundalu',
    image_url: '/sweets/sunnundalu.jpg',
    description: 'Traditional high-protein Andhra festive sweet made from slow-roasted whole black gram (urad dal), pure country cow ghee, and organic jaggery.',
    price: 340.00,
    weight: '500g',
    ingredients: 'Roasted Urad Dal, Pure Cow Ghee, Organic Bellam (Jaggery), Cardamom.',
    taste_profile: 'Hearty, nutty, earthy jaggery flavour with luxurious ghee aroma.',
    allergens: 'Contains Dairy (Ghee).',
    shelf_life: '30 Days from packing date.',
    storage_instructions: 'Store in an airtight container at room temperature.',
    stock: 65,
    is_available: true,
    rating: 4.95,
    review_count: 128,
    categories: { name: 'Traditional Sweets' },
    product_images: [{ image_url: '/sweets/sunnundalu.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000021',
    name: 'Bobbatlu',
    slug: 'bobbatlu',
    image_url: '/sweets/bobbatlu.jpg',
    description: 'Soft, golden flatbread stuffed with a sweet, aromatic filling of boiled chana dal, jaggery, cardamom, and roasted on a tawa with pure ghee.',
    price: 290.00,
    weight: 'Pack of 6 Pcs',
    ingredients: 'Chana Dal (Bengal Gram), Organic Jaggery, Maida, Cardamom, Pure Desi Cow Ghee, Nutmeg.',
    taste_profile: 'Soft, buttery flatbread with aromatic cardamom jaggery filling.',
    allergens: 'Contains Gluten and Dairy.',
    shelf_life: '7 Days from packing date.',
    storage_instructions: 'Store in airtight box. Warm slightly before enjoying.',
    stock: 55,
    is_available: true,
    rating: 4.95,
    review_count: 156,
    categories: { name: 'Traditional Sweets' },
    product_images: [{ image_url: '/sweets/bobbatlu.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000023',
    name: 'Bellam Gavvalu',
    slug: 'bellam-gavvalu',
    image_url: '/sweets/bellam-gavvalu.jpg',
    description: 'Crispy shell-shaped fried pastries coated in rich, glossy organic jaggery syrup and fragrant cardamom.',
    price: 260.00,
    weight: '500g',
    ingredients: 'Wheat Flour, Pure Ghee, Organic Jaggery (Bellam), Cardamom.',
    taste_profile: 'Crunchy, sweet, caramelised jaggery shell with satisfying bite.',
    allergens: 'Contains Gluten and Dairy.',
    shelf_life: '30 Days from packing date.',
    storage_instructions: 'Store in an airtight jar at room temperature.',
    stock: 80,
    is_available: true,
    rating: 4.88,
    review_count: 72,
    categories: { name: 'Traditional Sweets' },
    product_images: [{ image_url: '/sweets/bellam-gavvalu.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000024',
    name: 'Malai Puri',
    slug: 'malai-puri',
    image_url: '/sweets/malai-puri.jpg',
    description: 'Tender, flaky golden discs crafted from fresh milk cream (malai) and flour, immersed in aromatic saffron cardamom sugar syrup.',
    price: 340.00,
    weight: '500g',
    ingredients: 'Fresh Milk Malai, Maida, Pure Ghee, Sugar Syrup, Saffron, Pistachios.',
    taste_profile: 'Juicy, flaky, rich creaminess with subtle saffron fragrance.',
    allergens: 'Contains Gluten and Dairy.',
    shelf_life: '8 Days from packing date.',
    storage_instructions: 'Store in an airtight container or refrigerate.',
    stock: 45,
    is_available: true,
    rating: 4.86,
    review_count: 58,
    categories: { name: 'Traditional Sweets' },
    product_images: [{ image_url: '/sweets/malai-puri.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000025',
    name: 'White Rasakanda',
    slug: 'white-rasakanda',
    image_url: '/sweets/white-rasakanda.jpg',
    description: 'Delicate and juicy sweet made from pure cow milk chenna, gently cooked and soaked in light rose and cardamom scented syrup.',
    price: 300.00,
    weight: '500g',
    ingredients: 'Cow Milk Chenna (Cottage Cheese), Sugar, Rose Water, Cardamom.',
    taste_profile: 'Spongy, light, refreshing sweetness with delicate rose undertones.',
    allergens: 'Contains Dairy.',
    shelf_life: '6 Days from packing date.',
    storage_instructions: 'Refrigeration recommended.',
    stock: 50,
    is_available: true,
    rating: 4.84,
    review_count: 46,
    categories: { name: 'Traditional Sweets' },
    product_images: [{ image_url: '/sweets/white-rasakanda.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000026',
    name: 'White Angoor',
    slug: 'white-angoor',
    image_url: '/sweets/white-angoor.jpg',
    description: 'Grape-sized miniature spherical chenna dumplings poached in light, fragrant sugar syrup.',
    price: 290.00,
    weight: '500g',
    ingredients: 'Fresh Cow Milk Chenna, Cane Sugar, Rose Essence, Cardamom.',
    taste_profile: 'Spongy, sweet, bite-sized burst of mild dairy sweetness.',
    allergens: 'Contains Dairy.',
    shelf_life: '6 Days from packing date.',
    storage_instructions: 'Store in refrigerator in syrup.',
    stock: 55,
    is_available: true,
    rating: 4.85,
    review_count: 49,
    categories: { name: 'Traditional Sweets' },
    product_images: [{ image_url: '/sweets/white-angoor.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000027',
    name: 'Brown Angoor',
    slug: 'brown-angoor',
    image_url: '/sweets/brown-angoor.jpg',
    description: 'Miniature bite-sized golden brown khoya spheres fried in pure ghee and soaked in warm cardamom sugar syrup.',
    price: 300.00,
    weight: '500g',
    ingredients: 'Mawa (Khoya), Milk Solids, Pure Ghee, Sugar, Cardamom, Saffron.',
    taste_profile: 'Soft, juicy miniature bursts of caramelised milk sweetness.',
    allergens: 'Contains Dairy.',
    shelf_life: '8 Days from packing date.',
    storage_instructions: 'Store in a cool dry place or refrigerate.',
    stock: 60,
    is_available: true,
    rating: 4.87,
    review_count: 53,
    categories: { name: 'Traditional Sweets' },
    product_images: [{ image_url: '/sweets/brown-angoor.jpg', is_primary: true }],
  },

  // 3. Milk Sweets & Kalakand
  {
    id: 'c1000000-0000-0000-0000-000000000011',
    name: 'Mysore Pak',
    slug: 'mysore-pak',
    image_url: '/sweets/mysore-pak.jpg',
    description: 'Classic royal South Indian delicacy prepared with slow-roasted gram flour, generous pure desi ghee, and fine sugar.',
    price: 340.00,
    weight: '500g',
    ingredients: 'Gram Flour (Besan), Pure Desi Cow Ghee, Sugar, Cardamom.',
    taste_profile: 'Aromatic, buttery, traditional porous texture with caramel besan aroma.',
    allergens: 'Contains Dairy (Ghee).',
    shelf_life: '20 Days from packing date.',
    storage_instructions: 'Store at ambient room temperature in clean dry container.',
    stock: 70,
    is_available: true,
    rating: 4.90,
    review_count: 130,
    categories: { name: 'Milk Sweets & Kalakand' },
    product_images: [{ image_url: '/sweets/mysore-pak.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000012',
    name: 'Milk Mysore Pak',
    slug: 'milk-mysore-pak',
    image_url: '/sweets/milk-mysore-pak.jpg',
    description: 'Super soft and velvety variation of Mysore Pak infused with fresh condensed milk solids and pure ghee for a fudge-like texture.',
    price: 360.00,
    weight: '500g',
    ingredients: 'Milk Solids (Khoya), Besan, Pure Desi Ghee, Sugar, Cardamom.',
    taste_profile: 'Silky, creamy, melt-in-mouth milk and ghee bliss.',
    allergens: 'Contains Dairy (Milk, Ghee).',
    shelf_life: '15 Days from packing date.',
    storage_instructions: 'Store in a clean dry airtight container.',
    stock: 55,
    is_available: true,
    rating: 4.93,
    review_count: 118,
    categories: { name: 'Milk Sweets & Kalakand' },
    product_images: [{ image_url: '/sweets/milk-mysore-pak.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000013',
    name: 'Ongole Mysore Pak',
    slug: 'ongole-mysore-pak',
    image_url: '/sweets/ongole-mysore-pak.jpg',
    description: 'Authentic Andhra-style crispy and honeycomb-porous Mysore Pak with dark caramelised center and intense ghee aroma.',
    price: 320.00,
    weight: '500g',
    ingredients: 'Gram Flour (Besan), Pure Desi Ghee, Sugar.',
    taste_profile: 'Crisp, airy honeycomb structure with deeply roasted nutty ghee aroma.',
    allergens: 'Contains Dairy (Ghee).',
    shelf_life: '25 Days from packing date.',
    storage_instructions: 'Store in an airtight container at room temperature.',
    stock: 60,
    is_available: true,
    rating: 4.88,
    review_count: 82,
    categories: { name: 'Milk Sweets & Kalakand' },
    product_images: [{ image_url: '/sweets/ongole-mysore-pak.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000022',
    name: 'Pala Kova',
    slug: 'pala-kova',
    image_url: '/sweets/pala-kova.jpg',
    description: 'Pure farm-fresh whole milk slow-condensed for hours in heavy-bottomed kadai with cane sugar and a hint of cardamom to a luscious fudge.',
    price: 310.00,
    weight: '500g',
    ingredients: 'Fresh Cow Milk, Cane Sugar, Cardamom, Pure Ghee.',
    taste_profile: 'Rich, milky, creamy and deeply satisfying traditional dairy sweetness.',
    allergens: 'Contains Dairy (Milk, Ghee).',
    shelf_life: '10 Days from packing date.',
    storage_instructions: 'Keep in cool dry place. Refrigeration recommended.',
    stock: 70,
    is_available: true,
    rating: 4.92,
    review_count: 135,
    categories: { name: 'Milk Sweets & Kalakand' },
    product_images: [{ image_url: '/sweets/pala-kova.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000028',
    name: 'White Piece Kalakand',
    slug: 'white-piece-kalakand',
    image_url: '/sweets/white-piece-kalakand.jpg',
    description: 'Granular, moist traditional milk fudge made by slow-simmering whole milk with delicate paneer curds and cardamom.',
    price: 340.00,
    weight: '500g',
    ingredients: 'Fresh Whole Milk, Paneer Curds, Sugar, Cardamom, Pistachio garnish.',
    taste_profile: 'Granular (danedar), moist, rich and creamy dairy goodness.',
    allergens: 'Contains Dairy.',
    shelf_life: '7 Days from packing date.',
    storage_instructions: 'Refrigerate in an airtight container.',
    stock: 65,
    is_available: true,
    rating: 4.93,
    review_count: 115,
    categories: { name: 'Milk Sweets & Kalakand' },
    product_images: [{ image_url: '/sweets/white-piece-kalakand.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000029',
    name: 'Karjur Kalakand',
    slug: 'karjur-kalakand',
    image_url: '/sweets/karjur-kalakand.jpg',
    description: 'Decadent fusion kalakand blending rich reduced milk solids with natural Arabian dates and crushed pistachios.',
    price: 370.00,
    weight: '500g',
    ingredients: 'Fresh Milk, Arabian Dates (Karjur), Sugar, Pure Ghee, Pistachios.',
    taste_profile: 'Moist, rich, caramelised date sweetness combined with granular milk fudge.',
    allergens: 'Contains Dairy and Tree Nuts.',
    shelf_life: '10 Days from packing date.',
    storage_instructions: 'Keep refrigerated in an airtight box.',
    stock: 50,
    is_available: true,
    rating: 4.91,
    review_count: 74,
    categories: { name: 'Milk Sweets & Kalakand' },
    product_images: [{ image_url: '/sweets/karjur-kalakand.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000030',
    name: 'Horlicks Kalakand',
    slug: 'horlicks-kalakand',
    image_url: '/sweets/horlicks-kalakand.jpg',
    description: 'Nostalgic modern fusion sweet blending granular milk kalakand with premium malt Horlicks and roasted cashews.',
    price: 360.00,
    weight: '500g',
    ingredients: 'Fresh Milk, Malted Horlicks, Sugar, Ghee, Cashews, Cardamom.',
    taste_profile: 'Malty, creamy, granular fudge with a delightfully comforting aroma.',
    allergens: 'Contains Dairy and Tree Nuts.',
    shelf_life: '10 Days from packing date.',
    storage_instructions: 'Store in a cool dry place or refrigerate.',
    stock: 55,
    is_available: true,
    rating: 4.94,
    review_count: 98,
    categories: { name: 'Milk Sweets & Kalakand' },
    product_images: [{ image_url: '/sweets/horlicks-kalakand.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000031',
    name: 'Vanilla Icecream Burfi',
    slug: 'vanilla-icecream-burfi',
    image_url: '/sweets/vanilla-icecream-burfi.jpg',
    description: 'Ultra-smooth, melt-in-mouth creamy milk burfi flavoured with natural vanilla bean and garnished with almond slivers.',
    price: 350.00,
    weight: '500g',
    ingredients: 'Khoya (Mawa), Milk Solids, Pure Ghee, Sugar, Natural Vanilla, Almonds.',
    taste_profile: 'Silky, velvety, ice cream-like cool vanilla milk flavour.',
    allergens: 'Contains Dairy and Tree Nuts.',
    shelf_life: '12 Days from packing date.',
    storage_instructions: 'Keep refrigerated.',
    stock: 50,
    is_available: true,
    rating: 4.88,
    review_count: 64,
    categories: { name: 'Milk Sweets & Kalakand' },
    product_images: [{ image_url: '/sweets/vanilla-icecream-burfi.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000032',
    name: 'Badam Icecream Burfi',
    slug: 'badam-icecream-burfi',
    image_url: '/sweets/badam-icecream-burfi.jpg',
    description: 'Luxurious double-layered burfi combining rich California almond paste with smooth vanilla milk cream.',
    price: 380.00,
    weight: '500g',
    ingredients: 'California Almonds (Badam), Khoya, Sugar, Pure Cow Ghee, Saffron, Cardamom.',
    taste_profile: 'Rich, nutty almond goodness with a smooth creamy dairy finish.',
    allergens: 'Contains Tree Nuts and Dairy.',
    shelf_life: '15 Days from packing date.',
    storage_instructions: 'Keep refrigerated.',
    stock: 45,
    is_available: true,
    rating: 4.92,
    review_count: 86,
    categories: { name: 'Milk Sweets & Kalakand' },
    product_images: [{ image_url: '/sweets/badam-icecream-burfi.jpg', is_primary: true }],
  },

  // 4. Laddu Varieties
  {
    id: 'c1000000-0000-0000-0000-000000000014',
    name: 'Boondhi Laddu',
    slug: 'boondhi-laddu',
    image_url: '/sweets/boondhi-laddu.jpg',
    description: 'Generously sized golden gram flour boondi pearls tossed in pure ghee, cardamom, cloves, crunchy cashews, and juicy raisins.',
    price: 300.00,
    weight: '500g',
    ingredients: 'Gram Flour (Besan), Pure Cow Ghee, Cane Sugar, Cashews, Raisins, Cardamom, Cloves.',
    taste_profile: 'Aromatic, sweet, soft and slightly chewy with crunchy nut bursts.',
    allergens: 'Contains Tree Nuts and Dairy.',
    shelf_life: '15 Days from packing date.',
    storage_instructions: 'Store in airtight box away from moisture.',
    stock: 90,
    is_available: true,
    rating: 4.89,
    review_count: 120,
    categories: { name: 'Laddu Varieties' },
    product_images: [{ image_url: '/sweets/boondhi-laddu.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000015',
    name: 'Mothi Laddu',
    slug: 'mothi-laddu',
    image_url: '/sweets/mothi-laddu.jpg',
    description: 'Tiny golden gram flour pearls fried in pure ghee, bound with saffron-infused sugar syrup, melon seeds, and crushed green cardamom.',
    price: 320.00,
    weight: '500g',
    ingredients: 'Besan, Pure Desi Ghee, Sugar Syrup, Saffron, Cardamom, Magaj (Melon Seeds).',
    taste_profile: 'Juicy, soft, fragrant and melt-in-mouth sweetness.',
    allergens: 'Contains Dairy (Ghee).',
    shelf_life: '10 Days from packing date.',
    storage_instructions: 'Airtight container at room temperature.',
    stock: 80,
    is_available: true,
    rating: 4.93,
    review_count: 164,
    categories: { name: 'Laddu Varieties' },
    product_images: [{ image_url: '/sweets/mothi-laddu.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000016',
    name: 'Besan Laddu',
    slug: 'besan-laddu',
    image_url: '/sweets/besan-laddu.jpg',
    description: 'Golden roasted chickpea flour laddu slow-cooked in pure desi cow ghee, fragrant cardamom and crunchy almond flakes.',
    price: 310.00,
    weight: '500g',
    ingredients: 'Roasted Gram Flour (Besan), Pure Cow Ghee, Sugar, Cardamom, Almonds.',
    taste_profile: 'Nutty, rich, aromatic roasted ghee goodness with fine melt-in-mouth texture.',
    allergens: 'Contains Dairy and Tree Nuts.',
    shelf_life: '25 Days from packing date.',
    storage_instructions: 'Store in a cool dry container.',
    stock: 75,
    is_available: true,
    rating: 4.89,
    review_count: 95,
    categories: { name: 'Laddu Varieties' },
    product_images: [{ image_url: '/sweets/besan-laddu.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000017',
    name: 'Dry Fruit Laddu',
    slug: 'dry-fruit-laddu',
    image_url: '/sweets/dry-fruit-laddu.jpg',
    description: 'Nutrient-dense sugar-free energy balls loaded with crushed almonds, cashews, pistachios, dates, figs, and pure country ghee.',
    price: 480.00,
    weight: '500g',
    ingredients: 'Arabian Dates, Dried Figs (Anjeer), Cashews, Almonds, Pistachios, Pure Desi Ghee, Cardamom.',
    taste_profile: 'Naturally sweet from dates and figs with dense, nutty crunch.',
    allergens: 'Contains Tree Nuts and Dairy.',
    shelf_life: '30 Days from packing date.',
    storage_instructions: 'Store in an airtight container.',
    stock: 60,
    is_available: true,
    rating: 4.97,
    review_count: 188,
    categories: { name: 'Laddu Varieties' },
    product_images: [{ image_url: '/sweets/dry-fruit-laddu.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000018',
    name: 'Thokkudu Laddu',
    slug: 'thokkudu-laddu',
    image_url: '/sweets/thokkudu-laddu.jpg',
    description: 'Machilipatnam legendary pounded besan laddu, velvety smooth and melt-in-mouth, ground with roasted gram flour, ghee and fine powdered sugar.',
    price: 340.00,
    weight: '500g',
    ingredients: 'Roasted Besan Flour, Pure Desi Ghee, Fine Sugar, Cardamom, Cashews.',
    taste_profile: 'Silky, velvety, smooth floury texture that melts effortlessly.',
    allergens: 'Contains Dairy and Tree Nuts.',
    shelf_life: '20 Days from packing date.',
    storage_instructions: 'Store at ambient room temperature in clean dry container.',
    stock: 65,
    is_available: true,
    rating: 4.94,
    review_count: 145,
    categories: { name: 'Laddu Varieties' },
    product_images: [{ image_url: '/sweets/thokkudu-laddu.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000019',
    name: 'Balaji Laddu',
    slug: 'balaji-laddu',
    image_url: '/sweets/balaji-laddu.jpg',
    description: 'Grand festive prasadam-style boondi laddu made with generous pure cow ghee, edible camphor, cashews, raisins, and aromatic cardamom.',
    price: 350.00,
    weight: '500g',
    ingredients: 'Gram Flour, Pure Cow Ghee, Sugar, Cashews, Raisins, Edible Camphor, Cardamom, Kalkandu.',
    taste_profile: 'Divinely fragrant with ghee, camphor and rich nutty sweetness.',
    allergens: 'Contains Dairy and Tree Nuts.',
    shelf_life: '15 Days from packing date.',
    storage_instructions: 'Store in an airtight container.',
    stock: 55,
    is_available: true,
    rating: 4.96,
    review_count: 134,
    categories: { name: 'Laddu Varieties' },
    product_images: [{ image_url: '/sweets/balaji-laddu.jpg', is_primary: true }],
  },

  // 5. Halwa Specials
  {
    id: 'c1000000-0000-0000-0000-000000000033',
    name: 'Fruit Halwa',
    slug: 'fruit-halwa',
    image_url: '/sweets/fruit-halwa.jpg',
    description: 'Translucent, chewy royal halwa enriched with real fruit extracts, pineapple pulp, pure ghee, and roasted cashews.',
    price: 320.00,
    weight: '500g',
    ingredients: 'Corn Flour, Sugar, Mixed Fruit Pulp, Pure Ghee, Cashews, Cardamom.',
    taste_profile: 'Chewy, fruity, translucent and fragrant with pure ghee.',
    allergens: 'Contains Dairy and Tree Nuts.',
    shelf_life: '30 Days from packing date.',
    storage_instructions: 'Store at room temperature in an airtight box.',
    stock: 50,
    is_available: true,
    rating: 4.86,
    review_count: 68,
    categories: { name: 'Halwa Specials' },
    product_images: [{ image_url: '/sweets/fruit-halwa.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000034',
    name: 'Red Halwa',
    slug: 'red-halwa',
    image_url: '/sweets/red-halwa.jpg',
    description: 'Vibrant ruby-red translucent jelly-textured halwa cooked slowly in pure desi ghee with crunchy roasted cashews and melon seeds.',
    price: 310.00,
    weight: '500g',
    ingredients: 'Corn Starch, Sugar, Pure Desi Cow Ghee, Cashews, Cardamom, Edible Food Color.',
    taste_profile: 'Glossy, chewy, sweet with delightful crunch of ghee-roasted nuts.',
    allergens: 'Contains Dairy and Tree Nuts.',
    shelf_life: '30 Days from packing date.',
    storage_instructions: 'Store in a clean airtight container.',
    stock: 55,
    is_available: true,
    rating: 4.87,
    review_count: 72,
    categories: { name: 'Halwa Specials' },
    product_images: [{ image_url: '/sweets/red-halwa.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000035',
    name: 'Dry Fruit Halwa',
    slug: 'dry-fruit-halwa',
    image_url: '/sweets/dry-fruit-halwa.jpg',
    description: 'Slow-simmered dark amber halwa infused with generous amounts of cashews, almonds, pistachios, dates, and cardamom cooked to a rich caramelized fudge.',
    price: 460.00,
    weight: '500g',
    ingredients: 'Dates Pulp, Cashews, Almonds, Pistachios, Corn Flour, Pure Ghee, Cardamom.',
    taste_profile: 'Chewy, deeply nutty, aromatic caramel sweetness.',
    allergens: 'Contains Tree Nuts and Dairy.',
    shelf_life: '30 Days from packing date.',
    storage_instructions: 'Store in airtight box away from moisture.',
    stock: 45,
    is_available: true,
    rating: 4.91,
    review_count: 98,
    categories: { name: 'Halwa Specials' },
    product_images: [{ image_url: '/sweets/dry-fruit-halwa.jpg', is_primary: true }],
  },

  // 6. Pootharekulu
  {
    id: 'c1000000-0000-0000-0000-000000000036',
    name: 'Bellam Pootharekulu',
    slug: 'bellam-pootharekulu',
    image_url: '/sweets/bellam-pootharekulu.jpg',
    description: 'World-famous paper-thin rice starch film rolls from Atreyapuram folded with pure country cow ghee and organic jaggery powder.',
    price: 340.00,
    weight: 'Box of 10 Pcs',
    ingredients: 'Jaya Rice Starch Sheets, Pure Desi Cow Ghee, Organic Bellam (Jaggery), Cardamom.',
    taste_profile: 'Crisp wafer-thin paper melting into buttery warm jaggery sweetness.',
    allergens: 'Contains Dairy (Ghee).',
    shelf_life: '30 Days from packing date.',
    storage_instructions: 'Keep in a dry, moisture-free container. Handle gently.',
    stock: 60,
    is_available: true,
    rating: 4.96,
    review_count: 142,
    categories: { name: 'Pootharekulu' },
    product_images: [{ image_url: '/sweets/bellam-pootharekulu.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000037',
    name: 'Sugar Pootharekulu',
    slug: 'sugar-pootharekulu',
    image_url: '/sweets/sugar-pootharekulu.jpg',
    description: 'Delicate paper-sweet made with translucent rice starch sheets rolled with pure melted desi ghee and finely powdered cane sugar.',
    price: 320.00,
    weight: 'Box of 10 Pcs',
    ingredients: 'Rice Starch Sheets, Pure Desi Ghee, Fine Powdered Cane Sugar, Cardamom.',
    taste_profile: 'Feather-light crunchy rice wafer dissolving into sweet buttery cardamom.',
    allergens: 'Contains Dairy (Ghee).',
    shelf_life: '30 Days from packing date.',
    storage_instructions: 'Store in an airtight container.',
    stock: 55,
    is_available: true,
    rating: 4.90,
    review_count: 86,
    categories: { name: 'Pootharekulu' },
    product_images: [{ image_url: '/sweets/sugar-pootharekulu.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000038',
    name: 'Dry Fruit Bellam Pootharekulu',
    slug: 'dry-fruit-bellam-pootharekulu',
    image_url: '/sweets/dry-fruit-bellam-pootharekulu.jpg',
    description: 'Ultra-thin edible rice paper rolls stuffed with generous amounts of crushed cashews, almonds, pistachios, pure country ghee and powdered jaggery.',
    price: 450.00,
    weight: 'Box of 10 Pcs',
    ingredients: 'Rice Flour starch sheets, Pure Ghee, Organic Jaggery powder, Cashew Nuts, Almonds, Pistachios, Cardamom.',
    taste_profile: 'Delicate paper-thin texture dissolving into buttery nutty jaggery richness.',
    allergens: 'Contains Tree Nuts and Dairy.',
    shelf_life: '30 Days from packing date.',
    storage_instructions: 'Keep in moisture-free container. Handle gently.',
    stock: 42,
    is_available: true,
    rating: 4.98,
    review_count: 215,
    categories: { name: 'Pootharekulu' },
    product_images: [{ image_url: '/sweets/dry-fruit-bellam-pootharekulu.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000039',
    name: 'Dry Fruit Sugar Pootharekulu',
    slug: 'dry-fruit-sugar-pootharekulu',
    image_url: '/sweets/dry-fruit-sugar-pootharekulu.jpg',
    description: 'Delicate rice starch paper rolls generously loaded with chopped cashews, almonds, pistachios, pure ghee, and fine powdered sugar.',
    price: 440.00,
    weight: 'Box of 10 Pcs',
    ingredients: 'Rice Starch Sheets, Pure Desi Ghee, Powdered Sugar, Cashews, Almonds, Pistachios, Cardamom.',
    taste_profile: 'Wafer-thin, crisp, nutty and rich with sweet pure ghee.',
    allergens: 'Contains Tree Nuts and Dairy.',
    shelf_life: '30 Days from packing date.',
    storage_instructions: 'Store in a dry moisture-free box.',
    stock: 40,
    is_available: true,
    rating: 4.92,
    review_count: 94,
    categories: { name: 'Pootharekulu' },
    product_images: [{ image_url: '/sweets/dry-fruit-sugar-pootharekulu.jpg', is_primary: true }],
  },

  // 7. Savouries & Snacks
  {
    id: 'c1000000-0000-0000-0000-000000000040',
    name: 'Mixture',
    slug: 'mixture',
    image_url: '/sweets/mixture.jpg',
    description: 'Traditional festive mixture combining crunchy besan sev, boondi, fried peanuts, roasted cashews, curry leaves, garlic flakes and Andhra spice blend.',
    price: 195.00,
    weight: '400g',
    ingredients: 'Gram Flour, Peanuts, Cashews, Poha, Curry Leaves, Garlic, Red Chilli Powder, Salt, Pure Sunflower Oil.',
    taste_profile: 'Spicy, zesty, crunchy with aromatic garlic and curry leaf burst.',
    allergens: 'Contains Peanuts and Tree Nuts.',
    shelf_life: '45 Days from packing date.',
    storage_instructions: 'Airtight container at room temperature.',
    stock: 110,
    is_available: true,
    rating: 4.86,
    review_count: 95,
    categories: { name: 'Savouries & Snacks' },
    product_images: [{ image_url: '/sweets/mixture.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000041',
    name: 'Palli Pakodi',
    slug: 'palli-pakodi',
    image_url: '/sweets/palli-pakodi.jpg',
    description: 'Crunchy tea-time savoury made with premium peanuts coated in spiced gram flour batter, curry leaves and deep fried to golden perfection.',
    price: 190.00,
    weight: '400g',
    ingredients: 'Peanuts (Palli), Gram Flour, Rice Flour, Red Chilli Powder, Curry Leaves, Ginger Garlic, Salt, Oil.',
    taste_profile: 'Crunchy, nutty, spicy and deeply savoury.',
    allergens: 'Contains Peanuts.',
    shelf_life: '45 Days from packing date.',
    storage_instructions: 'Store in an airtight container.',
    stock: 95,
    is_available: true,
    rating: 4.90,
    review_count: 84,
    categories: { name: 'Savouries & Snacks' },
    product_images: [{ image_url: '/sweets/palli-pakodi.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000042',
    name: 'Agra Mixture',
    slug: 'agra-mixture',
    image_url: '/sweets/agra-mixture.jpg',
    description: 'Classic royal Agra style mixture crafted with crispy fried whole masoor dal, fine sev, cashews, muskmelon seeds and sweet-tangy spice blend.',
    price: 210.00,
    weight: '400g',
    ingredients: 'Masoor Dal (Brown Lentils), Gram Flour, Cashews, Melon Seeds, Amchur (Dry Mango), Chilli, Black Salt, Oil.',
    taste_profile: 'Crispy, tangy, mildly sweet and savory with a wonderful crunch.',
    allergens: 'Contains Tree Nuts.',
    shelf_life: '45 Days from packing date.',
    storage_instructions: 'Store in a cool dry airtight jar.',
    stock: 85,
    is_available: true,
    rating: 4.88,
    review_count: 76,
    categories: { name: 'Savouries & Snacks' },
    product_images: [{ image_url: '/sweets/agra-mixture.jpg', is_primary: true }],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000043',
    name: 'Special Andhra Ribbon Murukku',
    slug: 'special-andhra-ribbon-murukku',
    image_url: '/sweets/special-andhra-ribbon-murukku.jpg',
    description: 'Crunchy and light ribbon pakoda made with fresh rice flour, gram flour, sesame seeds, ajwain and mild red chilli seasoning.',
    price: 180.00,
    weight: '400g',
    ingredients: 'Rice Flour, Gram Flour, Pure Sesame Oil, Red Chilli Powder, Cumin, Ajwain, Salt, Asafoetida.',
    taste_profile: 'Savory, crispy, lightly spiced with fragrant ajwain and sesame notes.',
    allergens: 'May contain traces of sesame.',
    shelf_life: '45 Days from packing date.',
    storage_instructions: 'Store in airtight container to maintain maximum crunch.',
    stock: 90,
    is_available: true,
    rating: 4.78,
    review_count: 64,
    categories: { name: 'Savouries & Snacks' },
    product_images: [{ image_url: '/sweets/special-andhra-ribbon-murukku.jpg', is_primary: true }],
  },

  // 8. Gift Boxes & Hampers
  {
    id: 'c1000000-0000-0000-0000-000000000044',
    name: 'Royal Heritage Celebration Box',
    slug: 'royal-heritage-celebration-box',
    image_url: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&q=80',
    description: 'A luxurious handcrafted gift assortment containing Kakinada Gottam Kaja, Kaju Katli, Dry Fruit Pootharekulu and Pure Ghee Mysore Pak.',
    price: 999.00,
    weight: '1.2 kg Assorted',
    ingredients: 'Assortment of Cashews, Pure Desi Ghee, Wheat Flour, Sugar, Jaggery, Almonds, Cardamom.',
    taste_profile: 'Symphony of crispy, syrupy, smooth and nutty traditional flavours.',
    allergens: 'Contains Gluten, Tree Nuts, Dairy.',
    shelf_life: '15 Days from packing date.',
    storage_instructions: 'Store individual items as indicated inside the gift packaging.',
    stock: 35,
    is_available: true,
    rating: 4.99,
    review_count: 160,
    categories: { name: 'Gift Boxes & Hampers' },
    product_images: [{ image_url: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&q=80', is_primary: true }],
  },
];
